#!/bin/bash

# Check if the script is running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root."
   exit 1
fi

ssh_config="/etc/ssh/sshd_config"
ngrok_token="2W0MRBU9ULQHZjrVzgFwpDnMkZA_oW5yx3MQX9LMmFZQmwu7"  # Replace with your ngrok token

update_system() {
    echo "[+] Updating repos"
    apt-get update -y
    echo "[+] Upgrading system"
    apt-get upgrade -y
}

install_ssh_server() {
    echo "[+] Installing ssh-server"
    apt-get install openssh-server -y
}

change_password(){
    echo "[!] Change the current password? This password will be used to log in to SSH [Y/n]:"
    read pwd

    case "$pwd" in
        "y"|"Y")
            passwd
            ;;
        "n"|"N") echo "[!] Keeping the current password"
            ;;
        *) echo "[!] Keeping the current password"
            ;;
    esac
}

mk_ssh_backup() {
    echo "[!] Backup current SSH configuration"
    cp "$ssh_config" "$ssh_config-$(date +'%Y%m%d%H%M%S').bak"
}

install_ngrok() {
    echo "[+] Downloading ngrok"
    wget "https://bin.equinox.io/c/ YOUR_NGROK_DOWNLOAD_LINK /ngrok-stable-linux-amd64.tgz"
    tar xzf ngrok-stable-linux-amd64.tgz
    mv ngrok /usr/local/bin/ngrok
    echo "[!] ngrok installed"

    ngrok authtoken $ngrok_token
}

allow_root_login() {
    sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' "$ssh_config"
}

start_ssh_daemon() {
    service ssh start
}

start_ngrok() {
    /usr/local/bin/ngrok tcp 22
}

update_system
install_ssh_server
change_password
mk_ssh_backup
allow_root_login
start_ssh_daemon
install_ngrok
start_ngrok
